model_name: "flux-dev"
data_config:
  dataset_type: "custom"  # 指定使用自定义数据集
  num_workers: 4
  img_size: 384
  data_path: "/jhcnas5/chenzhixuan/data/mimic_annotations.json"  # 自定义数据集文件路径
  data_format: "json"  # 数据格式: "json", "csv", "txt", "folder"
  image_dir: "/jhcnas4/kyle/Xray/DATA/MIMIC-CXR/files"  # 图像根目录路径
  text_column: "report"  # 文本列名（用于json/csv格式）
  image_column: "image_path"  # 图像路径列名（用于json/csv格式）
  seed: 0
  patch_size: 1
clip_config:
  clip_image_size: 384
  clip_dim: 768
  t5_dim: 4096
report_to: wandb
scale_factor: 1.0   # scaled logit-normal sampling
train_batch_size: 12
output_dir: /jhcnas5/chenzhixuan/checkpoints/GenHancer/outputs/mimic_SigLIP_384_stage1/
max_train_steps: 100000
learning_rate: 1e-4
lr_scheduler: constant
lr_warmup_steps: 10
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 0.01
adam_epsilon: 1e-8
momentum: 0.9
weight_decay: 0.01
max_grad_norm: 1.0
logging_dir: logs
mixed_precision: "bf16"
checkpointing_steps: 5000
checkpoints_total_limit: 50
tracker_project_name: GenHancer
resume_from_checkpoint: latest
gradient_accumulation_steps: 2
rank: 1

